name: Bug Report
description: Something doesn't work like it should? Tell us!
title: "[Bug]: "
labels: ["bug", "unconfirmed"]
assignees:
  - vinyzu
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please first check if the same issue has already been reported and if the Bug Report is valid.

  - type: checkboxes
    attributes:
      label: Checklist before reporting
      description: Please make sure you've completed the following steps before submitting a bug report.
      options:
        - label: I have searched for [similar issues](https://github.com/Kaliiiiiiiiii-Vinyzu/patchright/issues?q=sort%3Arelevance%20is%3Aissue) and didn't find a duplicate.
          required: true
        - label: I have updated to the latest version of Patchright to verify the issue still exists.
          required: true
        - label: I have verified that this issue does not occur when using [Playwright](https://github.com/microsoft/playwright/) directly.
          required: true

  - type: input
    id: version
    attributes:
      label: Patchright Version
      description: Which version of Patchright are you using?
      placeholder: e.g. 1.57.0
    validations:
      required: true

  - type: input
    id: operating_system
    attributes:
      label: Operating System
      description: Which operating system is this occurring on? [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
      placeholder: All, macOS 14.2 (Apple Silicon)
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I try to use X feature, patchright fails with error message Y...
    validations:
      required: true

  - type: textarea
    id: test_file
    attributes:
      label: Test file (self-contained)
      description: |
        A minimal, self-contained code example that demonstrates the issue.
        Please provide the code necessary to reproduce the bug, including any relevant setup or configuration.
        Please use code blocks with the correct language for better readability.
      placeholder: |
        ```py
        from patchright.sync_api import sync_playwright

        with sync_playwright() as p:
            browser = p.chromium.launch()
            page = browser.new_page()
            # ...
            browser.close()
        ```
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: The method should return X or perform Y...
    validations:
      required: false

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead? Include full error messages and stack traces if applicable.
      placeholder: The method raised an exception...
    validations:
      required: false